services:
  db:
    image: mysql:8.0 
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}   
      MYSQL_USER: ${DB_LOGIN}           
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${HOST}      
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data: